### ISSUE TITLE
[BUG] ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by selfagency** [formio/resquel#7]
## Environment
Please provide as many details as you can:

- Hosting type
  - [X] Local deployment
    - Version: Latest

## Steps to Reproduce
```
require('envkey')
const express = require('express')
const resquel = require('resquel')
const Console = require('consola')

const app = express()
const port = process.env.PORT || 3031

app.use(
  resquel({
    db: {
      user: process.env.DBUSER,
      password: process.env.DBPASS,
      server: process.env.DBHOST,
      database: process.env.DBNAME,
      port: process.env.DBPORT
    },
    routes: [
      {
        method: 'get',
        endpoint: '/users',
        query: 'SELECT * FROM core_members;'
      }
    ]
  })
)

app.listen(port)
Console.log(`Listening on port ${port}`)
```

## Expected behavior
To start successfully

## Observed behavior

```
$ node index.js
Listening on port 3031                                                                                                                                                                                    17:45:24
internal/buffer.js:47
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt8 (internal/buffer.js:137:5)
    at Packet.isLast (/Users/daniel/code/ironmarch/api/node_modules/tedious/lib/packet.js:112:29)
    at ReadablePacketStream.<anonymous> (/Users/daniel/code/ironmarch/api/node_modules/tedious/lib/message-io.js:91:18)
    at ReadablePacketStream.emit (events.js:198:13)
    at addChunk (/Users/daniel/code/ironmarch/api/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/daniel/code/ironmarch/api/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push (/Users/daniel/code/ironmarch/api/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push (/Users/daniel/code/ironmarch/api/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at ReadablePacketStream._transform (/Users/daniel/code/ironmarch/api/node_modules/tedious/lib/message-io.js:57:16)
error Command failed with exit code 1.
```

**Comment by jhen1422** [comment]
@selfagency 
Thank you for the report. We've added a ticket in our platform backlog and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by mp3three** [comment]
Unable to replicate this issue against v2.0.1 (current latest) tag
